# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100

def distinct_powers(min_range, max_range):
    sequence = set()                        # stores unique values
    for a in range(min_range, max_range + 1):
        for b in range(min_range, max_range + 1):
            c = a**b
            sequence.add(c)
    return f"There are {len(sequence)} ditinct term"

print(distinct_powers(2,100)) # 9183
